In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import scanpy as sc
import anndata as ad

import os
from glob import glob

from Prep_Data import normalize, pgrins_prepare_input
import pgrins_run_grins

In [4]:
pd.read_parquet("Data/SimulResults_Racipe/Keggoro_abcd_10e6/001/Keggoro_abcd_init_conds_001.parquet")

,A2M,A2ML1,AAK1,AATBC,AATK,ABALON,ABAT,ABCA1,ABCA10,ABCA13,...,ZSCAN31,ZSCAN9,ZSWIM3,ZSWIM4,ZSWIM5,ZXDC,ZYX,ZZEF1,ZZZ3,InitCondNum
0,98.122093,8.872836,84.595786,20.589554,59.140100,42.640419,20.305573,74.737282,62.430270,96.639322,...,98.954637,59.268832,69.312094,18.756109,57.275226,52.965216,93.663812,82.564706,29.442747,1
1,41.640476,59.651348,25.509170,80.011456,25.986233,70.510651,55.451037,5.217759,18.129469,41.646671,...,24.678370,18.585269,7.082290,85.309831,44.416695,25.133794,48.036727,12.916153,96.008927,2
2,7.909106,32.622780,63.954914,48.560921,10.472130,85.030631,30.925306,47.109930,35.800959,10.349774,...,42.766923,48.849833,78.072540,26.897526,75.456738,95.444132,55.460876,52.986404,16.188193,3
3,52.020072,82.289572,27.878147,52.077471,80.938477,1.521426,93.920368,76.602493,92.047034,53.003608,...,67.687434,75.416559,47.531757,71.042803,13.872292,30.414622,11.416017,29.749388,61.097362,4
4,65.138953,50.401281,7.322374,64.518559,90.710917,36.925484,43.312706,34.446329,43.313955,34.649676,...,57.768602,33.633569,55.155193,88.095780,98.068015,9.903098,80.216339,41.604870,48.351151,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95.874800,94.238617,91.813287,11.844861,82.791239,57.285695,76.143384,21.701235,23.650570,44.273201,...,65.686614,57.778613,42.687629,45.059465,20.125367,26.612170,89.940587,23.205977,79.334067,96
96,94.344547,23.417021,54.102898,44.225506,27.130669,63.401457,42.069905,7.499048,90.769921,93.267102,...,95.289466,41.852910,93.004663,97.805787,12.869536,90.290779,82.537220,88.451916,14.727959,97
97,39.411705,72.939063,43.580039,57.144404,58.757111,47.912643,84.177625,64.631427,36.075253,44.607071,...,20.965673,82.389289,33.083081,6.308611,99.783303,37.670733,27.652158,18.826960,62.631567,98
98,11.673058,49.112597,95.240525,16.320453,80.555582,8.630196,9.787880,85.053157,19.184556,1.756662,...,39.131976,52.319687,60.555380,58.740372,31.835815,58.432680,69.681215,71.631533,31.051340,99
99,54.238270,99.843231,9.114255,85.095915,11.616284,79.758735,67.370587,43.197621,61.943013,62.731396,...,64.004938,25.510220,15.355558,39.151829,68.478303,18.288669,16.331833,48.419625,94.422948,100

In [ ]:
pd.read_parquet("Data/SimulResults_Racipe/Keggoro_abcd/001/Keggoro_abcd_params_001_1.parquet")

,Prod_A2M,Prod_A2ML1,Prod_AAK1,Prod_AATBC,Prod_AATK,Prod_ABALON,Prod_ABAT,Prod_ABCA1,Prod_ABCA10,Prod_ABCA13,...,ActFld_ZNF83_ZZEF1,Thr_ZNF83_ZZEF1,Hill_ZNF83_ZZEF1,ActFld_ZBTB33_ZZZ3,Thr_ZBTB33_ZZZ3,Hill_ZBTB33_ZZZ3,InhFld_ZNF639_ZZZ3,Thr_ZNF639_ZZZ3,Hill_ZNF639_ZZZ3,ParamNum
1000,781.331659,63.280936,7.531156,90.377423,51.555769,50.357496,61.865536,360303.305643,7.609042,20.367407,...,1.394635,51.026073,5.0,31.016818,8.959418,4.0,0.019709,67.783047,3.0,1001
1001,697.570938,11.061517,72.109335,17.872633,34.180005,37.497758,34.056866,977786.737948,65.803259,58.004886,...,90.643957,136.756236,1.0,78.728926,7.727784,4.0,0.010266,45.798076,4.0,1002
1002,125.579859,56.800271,75.974437,58.692375,42.408129,45.639618,37.993906,591117.868248,53.023459,1.513871,...,61.991936,178.310663,3.0,53.051822,63.493825,3.0,0.465252,123.434119,4.0,1003
1003,226.320132,95.536996,14.689228,97.223336,79.525190,57.347822,20.595579,211573.620925,1.000000,70.746528,...,35.918945,26.497368,4.0,75.802167,44.461090,3.0,0.037077,161.247244,4.0,1004
1004,212.989716,12.342998,11.030062,74.233337,38.121500,88.835188,53.302005,740393.925524,6.463863,62.753998,...,12.870182,33.034256,3.0,84.085191,22.308495,5.0,0.499577,137.083255,5.0,1005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,962.802176,52.781671,49.602638,95.155758,47.984646,25.089123,17.261986,963591.315609,21.538399,10.061031,...,77.978781,55.106179,1.0,1.798376,50.978108,1.0,0.222681,140.134595,2.0,1996
1996,17.784640,38.979366,65.794813,41.332969,76.190523,93.338785,51.848361,848766.514307,90.781651,6.426005,...,20.007379,85.720974,1.0,67.561111,64.785821,4.0,0.010483,88.609058,6.0,1997
1997,352.277665,62.545560,57.901387,54.981642,52.374391,3.005481,83.061889,192540.959902,7.875456,8.317523,...,53.425767,174.961622,2.0,64.084849,27.300565,1.0,0.050647,74.739528,5.0,1998
1998,398.610255,12.329790,93.945871,30.253239,16.757006,58.810931,16.699573,962591.029169,16.527891,41.540447,...,19.605153,169.686525,3.0,97.176716,41.091618,6.0,0.012389,134.914351,3.0,1999
1999,144.888506,91.165764,9.210581,14.244056,34.408579,95.137322,27.501704,175048.768431,14.315710,55.834360,...,32.103842,108.321884,4.0,1.021995,26.494958,4.0,0.013291,150.378671,4.0,2000

:

In [ ]:
import importlib
importlib.reload(normalize)
importlib.reload(data_prep)
importlib.reload(pgrins_run_grins)

# `pgrins_prepare_input`:

In [3]:
experimental = True
project_name = "Keggoro_abcd"

In [4]:
if experimental:
    pseqs = sorted([pseq_path.split("/")[-1] for pseq_path in glob(f"Data/Experimental/*")])
    print(pseqs)

topo_files = sorted([pseq_path.split("/")[-1].split(".")[0] for pseq_path in glob(f"Data/Topos/*.topo")])
print(topo_files)

['AdamsonWeissman2016_GSM2406681_10X010', 'NormanWeissman2019_filtered', 'ReplogleWeissman2022_K562_essential']
['dorothea_abcd', 'dorothea_tf2_abcd', 'kegg']

In [ ]:
# Normalize perturb seq adata:
if experimental:
    norm_data_dict = {}
    for pseq_file in pseqs:
        norm_data_dict[pseq_file] = normalize.normalize_adata_main(pseq_file)
else:
    norm_data_dict = None

Reading file:  Data/Experimental/AdamsonWeissman2016_GSM2406681_10X010/perturb_norm.h5ad
Reading file:  Data/Experimental/NormanWeissman2019_filtered/perturb_norm.h5ad
Reading file:  Data/Experimental/ReplogleWeissman2022_K562_essential/perturb_norm.h5ad

In [5]:
grn_df, norm_data_dict = prep_data_pgrins.prepare_datasets(project_name, topo_files, norm_data_dict)

/storage/mi/sommereg03/vbsc/lib/python3.13/site-packages/scanpy/preprocessing/_highly_variable_genes.py:805: ImplicitModificationWarning: Trying to modify attribute `._uns` of view, initializing view as actual.
  adata.uns["hvg"] = {"flavor": flavor}
/storage/mi/sommereg03/vbsc/lib/python3.13/site-packages/scanpy/preprocessing/_highly_variable_genes.py:805: ImplicitModificationWarning: Trying to modify attribute `._uns` of view, initializing view as actual.
  adata.uns["hvg"] = {"flavor": flavor}
/storage/mi/sommereg03/vbsc/lib/python3.13/site-packages/scanpy/preprocessing/_highly_variable_genes.py:805: ImplicitModificationWarning: Trying to modify attribute `._uns` of view, initializing view as actual.
  adata.uns["hvg"] = {"flavor": flavor}

# `prins_run_grins`:

In [4]:
import pandas as pd
abc = pd.read_parquet("Data/SimulResults_Racipe/Keggoro_abcd/001/Keggoro_abcd_params_001.parquet")

In [5]:
abc

,Prod_A2M,Prod_A2ML1,Prod_AAK1,Prod_AATBC,Prod_AATK,Prod_ABALON,Prod_ABAT,Prod_ABCA1,Prod_ABCA10,Prod_ABCA13,...,ActFld_ZNF83_ZZEF1,Thr_ZNF83_ZZEF1,Hill_ZNF83_ZZEF1,ActFld_ZBTB33_ZZZ3,Thr_ZBTB33_ZZZ3,Hill_ZBTB33_ZZZ3,InhFld_ZNF639_ZZZ3,Thr_ZNF639_ZZZ3,Hill_ZNF639_ZZZ3,ParamNum
0,769.716196,93.391181,47.911364,87.771115,5.161404,21.564712,52.991580,234018.748419,29.053264,54.852582,...,90.844288,144.940105,1.0,41.048585,31.431202,2.0,0.018083,129.970461,1.0,1
1,111.295753,19.899084,68.773558,59.797354,97.985584,20.053144,64.325690,460129.906835,3.913076,93.395129,...,80.419255,135.601956,2.0,83.330075,56.548614,4.0,0.011536,109.981698,4.0,2
2,268.974469,47.184489,38.109993,22.026439,3.996049,9.357882,92.888223,718694.477789,98.099220,84.050458,...,93.022076,122.718465,2.0,79.311685,70.456304,5.0,0.027033,115.124860,1.0,3
3,962.059821,53.564349,63.644661,50.222522,95.373974,3.533624,37.070505,727135.908871,85.263339,95.024980,...,30.036536,8.785693,2.0,25.522829,23.461934,3.0,0.020351,53.113040,6.0,4
4,659.949927,42.523048,33.054448,86.363374,8.553005,17.899693,8.573340,682957.772684,29.340959,30.562514,...,69.620461,132.865875,4.0,60.306187,24.820233,4.0,0.030226,22.967461,2.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,350.868004,98.992931,34.585132,19.810926,13.155971,87.602379,72.071277,104960.754046,50.914137,31.033699,...,67.829742,170.688722,5.0,50.564676,72.667856,3.0,0.025785,128.776415,6.0,9996
9996,326.843856,60.786566,39.988163,7.750617,98.671503,72.526572,46.893921,454237.349636,57.095755,62.677919,...,61.650435,125.933550,6.0,8.463722,67.764268,3.0,0.017340,147.132689,3.0,9997
9997,653.557126,35.925020,93.645939,9.353619,25.541854,85.481875,43.607209,437604.616346,45.991004,61.713477,...,92.813383,147.801097,5.0,81.104232,69.623325,2.0,0.010339,115.215471,2.0,9998
9998,372.504190,21.697736,46.460729,60.579366,73.755419,23.294459,79.723988,831813.398072,25.283899,83.049621,...,55.714245,97.177691,2.0,5.336697,61.880669,4.0,0.041472,65.804904,2.0,9999
9999,367.286848,70.986624,84.486392,66.485154,79.031161,88.000268,8.127973,418177.958856,70.151258,52.039488,...,50.883948,177.163285,1.0,85.852118,38.698503,4.0,0.031906,64.698347,3.0,10000

In [ ]:
is_control = True
is_racipe = True
mode = "async"

In [ ]:
if is_control:
    if racipe:
        racipe_control(project_name)
    else:
        ising_control(project_name, mode)

# `pgrins_prepare_output`:

In [ ]:
# Evaluate control GRiNS:
is_discrete = False # If Ising: whether or not sync data should be loaded
zero_cutoff = 0.1
replicate = 1

In [ ]:
grins_data = pgrins_prepare_output.grins_to_adata(project_name, replicate, is_racipe, is_discrete, zero_cutoff)